ARG BASE_IMAGE
FROM $BASE_IMAGE
ARG DEBIAN_FRONTEND=noninteractive
RUN sed -i '/security/d' /etc/apt/sources.list \
    && sed -i 's/archive.ubuntu.com/mirror.iscas.ac.cn/g' /etc/apt/sources.list \
    && sed -i 's/ports.ubuntu.com/mirror.iscas.ac.cn/g' /etc/apt/sources.list \
    && apt-get update \
    && apt-get install -y --no-install-recommends qemu-user-static binfmt-support \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*
CMD update-binfmts --package=qemu-user-static --enable
